# Generated by Django 5.2.14 on 2026-05-28 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("core", "0002_initial"),
        ("doctors", "0001_initial"),
        ("laboratory", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CBCResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wbc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="×10³/µL",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "neutrophils_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "lymphocytes_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "monocytes_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "eosinophils_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "basophils_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "rbc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="×10⁶/µL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "hemoglobin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="g/dL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "hematocrit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "mcv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="fL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "mch",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="pg",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "mchc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="g/dL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "rdw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "platelets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="×10³/µL",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "mpv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="fL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("analyzer_name", models.CharField(blank=True, max_length=100)),
                (
                    "flags",
                    models.TextField(blank=True, help_text="Analyzer flags / comments"),
                ),
                (
                    "raw_output",
                    models.TextField(blank=True, help_text="Raw CSV/HL7 from machine"),
                ),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbc_results",
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbc_results",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChemistryResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "panel",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Metabolic Panel"),
                            ("comprehensive", "Comprehensive Metabolic Panel"),
                            ("lipid", "Lipid Panel"),
                            ("liver", "Liver Function Tests"),
                            ("kidney", "Kidney Function Tests"),
                            ("thyroid", "Thyroid Panel"),
                            ("cardiac", "Cardiac Markers"),
                            ("custom", "Custom"),
                        ],
                        default="comprehensive",
                        max_length=15,
                    ),
                ),
                (
                    "glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "bun",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "creatinine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "egfr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mL/min",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "sodium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mEq/L",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "potassium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mEq/L",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "chloride",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mEq/L",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "co2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mEq/L",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "calcium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "alt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="U/L",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "ast",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="U/L",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "alp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="U/L",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "bilirubin_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "bilirubin_direct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "albumin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="g/dL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "total_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="g/dL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "cholesterol_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mg/dL",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "hdl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mg/dL",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "ldl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mg/dL",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "triglycerides",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mg/dL",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "tsh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="mIU/L",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "t3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ng/dL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "t4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="µg/dL",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "troponin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ng/mL",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "ck_mb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="U/L",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("analyzer_name", models.CharField(blank=True, max_length=100)),
                ("flags", models.TextField(blank=True)),
                ("raw_output", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemistry_results",
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemistry_results",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IPDAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_number", models.CharField(max_length=20, unique=True)),
                ("ward", models.CharField(blank=True, max_length=100)),
                ("room_number", models.CharField(max_length=20)),
                ("bed_number", models.CharField(max_length=20)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("general", "General Ward"),
                            ("private", "Private Room"),
                            ("semi_private", "Semi-Private"),
                            ("icu", "ICU"),
                            ("nicu", "NICU"),
                            ("emergency", "Emergency"),
                            ("isolation", "Isolation"),
                            ("ot", "Operation Theatre"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                ("admission_date", models.DateTimeField(auto_now_add=True)),
                ("expected_discharge", models.DateField(blank=True, null=True)),
                ("discharge_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("admitted", "Admitted"),
                            ("transferred", "Transferred"),
                            ("discharged", "Discharged"),
                            ("absconded", "Absconded"),
                            ("deceased", "Deceased"),
                        ],
                        default="admitted",
                        max_length=15,
                    ),
                ),
                ("admission_diagnosis", models.TextField()),
                ("final_diagnosis", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admitting_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ipd_admissions",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "attending_nurse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ipd_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipd_admissions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-admission_date"],
            },
        ),
        migrations.CreateModel(
            name="DischargeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discharge_date", models.DateTimeField(auto_now_add=True)),
                ("discharge_condition", models.CharField(blank=True, max_length=100)),
                ("discharge_diagnosis", models.TextField()),
                ("treatment_summary", models.TextField()),
                ("discharge_instructions", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("diet_instructions", models.TextField(blank=True)),
                ("activity_restrictions", models.TextField(blank=True)),
                ("discharge_medications", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discharged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follow_up_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctors.doctor",
                    ),
                ),
                (
                    "admission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_record",
                        to="clinical.ipdadmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_number", models.CharField(max_length=20, unique=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="routine",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                ("clinical_summary", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consulting_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations_received",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "requesting_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations_requested",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_requests",
                        to="clinical.ipdadmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("report", "Lab / Diagnostic Report"),
                            ("image", "Medical Image"),
                            ("xray", "X-Ray"),
                            ("ecg", "ECG"),
                            ("scan", "CT / MRI Scan"),
                            ("document", "Document"),
                            ("consent", "Consent Form"),
                            ("prescription", "Prescription"),
                            ("discharge", "Discharge Summary"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="medical_files/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_files",
                        to="clinical.ipdadmission",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_files",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OPDVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_number", models.CharField(max_length=20, unique=True)),
                ("visit_date", models.DateField(auto_now_add=True)),
                ("arrival_time", models.TimeField(auto_now_add=True)),
                (
                    "triage_level",
                    models.CharField(
                        choices=[
                            ("1_resuscitation", "Level 1 – Resuscitation"),
                            ("2_emergent", "Level 2 – Emergent"),
                            ("3_urgent", "Level 3 – Urgent"),
                            ("4_less_urgent", "Level 4 – Less Urgent"),
                            ("5_non_urgent", "Level 5 – Non-Urgent"),
                        ],
                        default="5_non_urgent",
                        max_length=20,
                    ),
                ),
                ("chief_complaint", models.TextField()),
                ("vital_signs", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("with_doctor", "With Doctor"),
                            ("completed", "Completed"),
                            ("referred", "Referred"),
                            ("admitted", "Admitted"),
                        ],
                        default="waiting",
                        max_length=15,
                    ),
                ),
                ("referred_to", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opd_visit",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opd_visits",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opd_visits",
                        to="patients.patient",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opd_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("progress", "Progress Note"),
                            ("soap", "SOAP Note"),
                            ("nursing", "Nursing Note"),
                            ("assessment", "Nursing Assessment"),
                            ("diet", "Diet Note"),
                            ("social", "Social Work Note"),
                            ("physio", "Physiotherapy Note"),
                            ("other", "Other"),
                        ],
                        default="progress",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("subjective", models.TextField(blank=True)),
                ("objective", models.TextField(blank=True)),
                ("assessment", models.TextField(blank=True)),
                ("plan", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("vital_signs", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_notes",
                        to="patients.patient",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_notes",
                        to="clinical.ipdadmission",
                    ),
                ),
                (
                    "opd_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_notes",
                        to="clinical.opdvisit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_number", models.CharField(max_length=20, unique=True)),
                ("procedure_name", models.CharField(max_length=300)),
                ("operation_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("assistant_surgeon", models.CharField(blank=True, max_length=200)),
                ("anesthetist", models.CharField(blank=True, max_length=200)),
                ("anesthesia_type", models.CharField(blank=True, max_length=100)),
                ("scrub_nurse", models.CharField(blank=True, max_length=200)),
                ("circulating_nurse", models.CharField(blank=True, max_length=200)),
                ("pre_op_diagnosis", models.TextField()),
                ("post_op_diagnosis", models.TextField(blank=True)),
                ("indication", models.TextField(blank=True)),
                ("procedure_details", models.TextField(blank=True)),
                ("findings", models.TextField(blank=True)),
                ("complications", models.TextField(blank=True)),
                ("blood_loss", models.CharField(blank=True, max_length=50)),
                ("specimens_sent", models.TextField(blank=True)),
                ("drains", models.TextField(blank=True)),
                ("closure", models.TextField(blank=True)),
                ("post_op_instructions", models.TextField(blank=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_notes",
                        to="clinical.ipdadmission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_notes",
                        to="patients.patient",
                    ),
                ),
                (
                    "surgeon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgeries",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-operation_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientHandover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (07:00–15:00)"),
                            ("afternoon", "Afternoon (15:00–23:00)"),
                            ("night", "Night (23:00–07:00)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("handover_date", models.DateField(auto_now_add=True)),
                ("handover_time", models.TimeField(auto_now_add=True)),
                ("current_condition", models.TextField()),
                ("vital_signs", models.JSONField(blank=True, default=dict)),
                ("active_issues", models.TextField(blank=True)),
                ("pending_tasks", models.TextField(blank=True)),
                ("medications_due", models.TextField(blank=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handovers",
                        to="clinical.ipdadmission",
                    ),
                ),
                (
                    "handover_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handovers_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handover_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handovers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handovers",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=20, unique=True)),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("xray", "X-Ray"),
                            ("ct", "CT Scan"),
                            ("mri", "MRI"),
                            ("ultrasound", "Ultrasound"),
                            ("ecg", "ECG"),
                            ("echo", "Echocardiography"),
                            ("mammogram", "Mammogram"),
                            ("dexa", "DEXA Scan"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("body_part", models.CharField(max_length=150)),
                ("clinical_indication", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("in_progress", "In Progress"),
                            ("reported", "Reported"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="routine",
                        max_length=10,
                    ),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="radiology_orders",
                        to="clinical.ipdadmission",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiology_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "radiologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="radiology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="radiology_orders",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="radiology/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="clinical.radiologyorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadiologyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("findings", models.TextField()),
                ("impression", models.TextField()),
                ("recommendations", models.TextField(blank=True)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Upload JPEG/PNG/PDF/DICOM image",
                        null=True,
                        upload_to="radiology/%Y/%m/",
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "additional_images",
                    models.ManyToManyField(blank=True, to="clinical.radiologyimage"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="clinical.radiologyorder",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
