# Generated by Django 5.2.14 on 2026-06-07 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="opdvisit",
            name="card_paid",
            field=models.BooleanField(
                default=False, help_text="Card fee paid at cashier"
            ),
        ),
        migrations.AddField(
            model_name="opdvisit",
            name="triage_nurse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opd_triage",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
