# Generated by Django 5.2.14 on 2026-06-06 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted — Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "cash_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "card_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "mobile_money_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bank_transfer_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "check_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "instant_service_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("transaction_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        limit_choices_to={"role": "cashier"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-collection_date", "cashier"],
                "unique_together": {("cashier", "collection_date")},
            },
        ),
    ]
