# Generated by Django 5.2.14 on 2026-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-hospital",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HospitalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="City General Hospital", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="Your Health, Our Priority", max_length=300
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="hospital/"),
                ),
                ("address", models.TextField(default="123 Medical Drive, Health City")),
                ("phone", models.CharField(default="+1-800-HOSPITAL", max_length=20)),
                (
                    "email",
                    models.EmailField(default="info@hospital.com", max_length=254),
                ),
                ("website", models.URLField(blank=True)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("established_year", models.CharField(blank=True, max_length=4)),
                ("primary_color", models.CharField(default="#0d6efd", max_length=7)),
                ("secondary_color", models.CharField(default="#198754", max_length=7)),
                ("currency_symbol", models.CharField(default="$", max_length=5)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("working_hours", models.CharField(default="24/7", max_length=100)),
                ("emergency_number", models.CharField(default="911", max_length=20)),
                ("bed_capacity", models.IntegerField(default=100)),
                ("about", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hospital Settings",
                "verbose_name_plural": "Hospital Settings",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("billing", "Billing"),
                            ("lab", "Lab Result"),
                            ("pharmacy", "Pharmacy"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("link", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
