# Generated by Django 5.2.14 on 2026-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                choices=[
                    ("antibiotic", "Antibiotic"),
                    ("antiviral", "Antiviral"),
                    ("antimalarial", "Anti-Malarial"),
                    ("antifungal", "Anti-Fungal"),
                    ("antiparasitic", "Anti-Parasitic"),
                    ("analgesic", "Analgesic / Anti-Pain"),
                    ("antiinflammatory", "Anti-Inflammatory"),
                    ("steroid", "Steroid"),
                    ("anticonvulsant", "Anti-Convulsant"),
                    ("cardiovascular", "Cardiovascular Drug"),
                    ("antihypertensive", "Anti-Hypertensive"),
                    ("gi", "Gastrointestinal Drug"),
                    ("respiratory", "Respiratory Drug"),
                    ("antidiabetic", "Anti-Diabetic Drug"),
                    ("emergency", "Emergency Drug"),
                    ("fluid", "IV Fluid"),
                    ("cephalosporin", "Cephalosporin"),
                    ("eye_ear", "Eye / Ear Preparation"),
                    ("vitamin", "Vitamin & Supplement"),
                    ("psychiatric", "Psychiatric Drug"),
                    ("hormonal", "Hormonal Drug"),
                    ("dermatological", "Dermatological"),
                    ("other", "Other"),
                ],
                default="antibiotic",
                max_length=20,
            ),
        ),
    ]
